export const SELECT_RACE = 'SELECT_RACE'

export const LOAD_LEAFLET_MAP = 'LOAD_LEAFLET_MAP'

export const MAP_RACE = 'MAP_RACE'
export const MAP_CANDIDATE = 'MAP_CANDIDATE'

export const GEOCODE_STREET = 'GEOCODE_STREET'

export const SEARCH_DATABASE = 'SEARCH_DATABASE'
export const REQUEST_AUTOCOMPLETIONS = 'REQUEST_AUTOCOMPLETIONS'

export const FETCHED_GEOJSON = 'FETCHED_GEOJSON'
export const FETCHED_RACE = 'FETCHED_RACE'
export const FETCHED_RACE_HEAT_MAP = 'FETCHED_RACE_HEAT_MAP'
export const FETCHED_CANDIDATE_HEAT_MAP = 'FETCHED_CANDIDATE_HEAT_MAP'
export const FETCHED_AUTOCOMPLETIONS = 'FETCHED_AUTOCOMPLETIONS'
export const FETCHED_SEARCH_RESULTS = 'FETCHED_SEARCH_RESULTS'
