export const AUTOCOMPLETE = 'AUTOCOMPLETE'
export const CLEAR_AUTOCOMPLETIONS = 'CLEAR_AUTOCOMPLETIONS'
export const SEARCH_DATABASE = 'SEARCH_DATABASE'


export const SELECT_RACE_MAP = 'SELECT_RACE_MAP'
export const SELECT_CANDIDATE_MAP = 'SELECT_CANDIDATE_MAP'
export const REMOVE_HEAT_MAP = 'REMOVE_HEAT_MAP'
export const SELECT_ZONE = 'SELECT_ZONE'
export const GEOCODE = 'GEOCODE'


export const SELECT_GRAPH = 'SELECT_GRAPH'


export const UPDATE_AUTOCOMPLETIONS = 'UPDATE_AUTOCOMPLETIONS'
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS'

export const UPDATE_HEAT_MAP = 'UPDATE_HEAT_MAP'
export const UPDATE_ZONE_RESULTS = 'UPDATE_ZONE_RESULTS'
export const UPDATE_GEOCODE = 'UPDATE_GEOCODE'
export const UPDATE_GEOJSON = 'UPDATE_GEOJSON'

export const UPDATE_GRAPH = 'UPDATE_GRAPH'
