export const REQUEST_AUTOCOMPLETIONS = 'autocomplete'
export const REQUEST_SEARCH_RESULTS = 'search'

export const REQUEST_RACE_WARD_MAP = 'raceWardMap'
export const REQUEST_RACE_PRECINCT_MAP = 'racePrecinctMap'
export const REQUEST_CANDIDATE_WARD_MAP = 'candidateWardMap'
export const REQUEST_CANDIDATE_PRECINCT_MAP = 'candidatePrecinctMap'

export const REQUEST_GEOJSON = 'geojson'
export const REQUEST_GEOCODE = 'geocode'
export const REQUEST_WARD = 'ward'
export const REQUEST_PRECINCT = 'precinct'

export const REQUEST_RACE_WARD_GRAPH = 'raceWardGraph'



export const FETCHED_AUTOCOMPLETIONS = 'FETCHED_AUTOCOMPLETIONS'
export const FETCHED_SEARCH_RESULTS = 'FETCHED_SEARCH_RESULTS'

export const FETCHED_RACE_WARD_MAP = 'FETCHED_RACE_WARD_MAP'
export const FETCHED_RACE_PRECINCT_MAP = 'FETCHED_RACE_PRECINCT_MAP'
export const FETCHED_CANDIDATE_WARD_MAP = 'FETCHED_CANDIDATE_WARD_MAP'
export const FETCHED_CANDIDATE_PRECINCT_MAP = 'FETCHED_CANDIDATE_PRECINCT_MAP'

export const FETCHED_GEOJSON = 'FETCHED_GEOJSON'
export const FETCHED_GEOCODE = 'FETCHED_GEOCODE'
export const FETCHED_WARD = 'FETCHED_WARD'
export const FETCHED_PRECINCT = 'FETCHED_PRECINCT'

export const FETCHED_RACE_WARD_GRAPH = 'FETCHED_RACE_WARD_GRAPH'



export const FAILED_REQUEST = 'FAILED_REQUEST'
